//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirimMaliyet
    {
        public int BM_Id { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public Nullable<decimal> Dimmg { get; set; }
        public Nullable<decimal> Dig { get; set; }
        public Nullable<int> BirimDagitimOlcu { get; set; }
    
        public virtual DagıtımOlcu DagıtımOlcu { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
