//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirimMaliyetTutar
    {
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> EndirektToplam { get; set; }
        public Nullable<decimal> Dimmg { get; set; }
        public Nullable<decimal> Dig { get; set; }
        public Nullable<decimal> ToplamMaliyet { get; set; }
        public Nullable<int> BirimDagitimOlcu { get; set; }
        public int MaliyetUrunId { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> DagitimOlcuId { get; set; }
        public Nullable<decimal> UrunDagitimAdet { get; set; }
        public Nullable<decimal> BirimMaliyet { get; set; }
    }
}
