//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelTutar
    {
        public int MaliyetId { get; set; }
        public Nullable<decimal> Oran { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> GiderId { get; set; }
        public string FaaliyetAd { get; set; }
        public Nullable<int> FaaliyetId { get; set; }
        public Nullable<int> KMEId { get; set; }
        public string KMEAd { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<int> Adet { get; set; }
        public int Expr2 { get; set; }
        public string HesapKodu { get; set; }
        public string HesapAd { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<decimal> Geneltutar1 { get; set; }
    }
}
