//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaliyetUrun
    {
        public int MaliyetUrunId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> DagitimOlcuId { get; set; }
        public Nullable<decimal> UrunDagitimAdet { get; set; }
    
        public virtual DagıtımOlcu DagıtımOlcu { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
