//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maliyet
    {
        public int MaliyetId { get; set; }
        public Nullable<int> GiderId { get; set; }
        public Nullable<int> FaaliyetId { get; set; }
        public Nullable<int> KMEId { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Faaliyet Faaliyet { get; set; }
        public virtual Gider Gider { get; set; }
        public virtual KaynakMaliyetEtken KaynakMaliyetEtken { get; set; }
    }
}
