//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KuzeyMakEntities : DbContext
    {
        public KuzeyMakEntities()
            : base("name=KuzeyMakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BirimMaliyet> BirimMaliyet { get; set; }
        public virtual DbSet<DagıtımOlcu> DagıtımOlcu { get; set; }
        public virtual DbSet<DagitimOlcuFaaliyetiliski> DagitimOlcuFaaliyetiliski { get; set; }
        public virtual DbSet<Faaliyet> Faaliyet { get; set; }
        public virtual DbSet<Gider> Gider { get; set; }
        public virtual DbSet<KaynakMaliyetEtken> KaynakMaliyetEtken { get; set; }
        public virtual DbSet<Maliyet> Maliyet { get; set; }
        public virtual DbSet<MaliyetEndirektUretim> MaliyetEndirektUretim { get; set; }
        public virtual DbSet<MaliyetUrun> MaliyetUrun { get; set; }
        public virtual DbSet<TblBirimMaliyetTutar> TblBirimMaliyetTutar { get; set; }
        public virtual DbSet<TblToplamMaliyet> TblToplamMaliyet { get; set; }
        public virtual DbSet<TutarUrunFaaliyet> TutarUrunFaaliyet { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<BirimMaliyetTutar> BirimMaliyetTutar { get; set; }
        public virtual DbSet<EndirektUretimMaliyeti> EndirektUretimMaliyeti { get; set; }
        public virtual DbSet<GenelTutar> GenelTutar { get; set; }
        public virtual DbSet<Oran> Oran { get; set; }
        public virtual DbSet<OranUrunDagitim> OranUrunDagitim { get; set; }
        public virtual DbSet<ToplamFaaliyetTutar> ToplamFaaliyetTutar { get; set; }
        public virtual DbSet<ToplamMaliyet> ToplamMaliyet { get; set; }
        public virtual DbSet<UrunFaaliyetTutar> UrunFaaliyetTutar { get; set; }
    
        public virtual ObjectResult<BirimMaliyetSP_Result> BirimMaliyetSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BirimMaliyetSP_Result>("BirimMaliyetSP");
        }
    
        public virtual ObjectResult<ProductPrice_Result> ProductPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductPrice_Result>("ProductPrice");
        }
    
        public virtual ObjectResult<SPToplamMaliyet_Result> SPToplamMaliyet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPToplamMaliyet_Result>("SPToplamMaliyet");
        }
    
        public virtual ObjectResult<BirimMaliyetSP_Result> BirimMaliyetSP1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BirimMaliyetSP_Result>("BirimMaliyetSP1");
        }
    
        public virtual ObjectResult<ProductPrice_Result> ProductPrice1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductPrice_Result>("ProductPrice1");
        }
    
        public virtual ObjectResult<SPToplamMaliyet_Result> SPToplamMaliyet1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPToplamMaliyet_Result>("SPToplamMaliyet1");
        }
    
        public virtual ObjectResult<BirimMaliyetSP_Result> BirimMaliyetSP2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BirimMaliyetSP_Result>("BirimMaliyetSP2");
        }
    
        public virtual ObjectResult<Endirekt_Result> Endirekt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Endirekt_Result>("Endirekt");
        }
    
        public virtual ObjectResult<Endirekt_Result> Endirekt1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Endirekt_Result>("Endirekt1");
        }
    }
}
