//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblToplamMaliyet
    {
        public int TMaliyet_ID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<decimal> EndirektToplami { get; set; }
        public Nullable<decimal> Dimmg { get; set; }
        public Nullable<decimal> Dig { get; set; }
        public Nullable<decimal> ToplamMaliyeti { get; set; }
    }
}
