//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutarUrunFaaliyet
    {
        public int TUF_ID { get; set; }
        public string Urun { get; set; }
        public string Faaliyet { get; set; }
        public Nullable<decimal> TutarTUF { get; set; }
    }
}
