//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunFaaliyetTutar
    {
        public string UrunAd { get; set; }
        public string FaaliyetAd { get; set; }
        public int FaaliyetId { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public Nullable<long> Number { get; set; }
    }
}
